### ISSUE TITLE
What is status of this project?

### ISSUE THREAD

**Issue by janedoe-lab** [qsocket/qs-proxy#1]
I attempted to run qs-proxy, and got couple errors before it all falling appart since it tries to connect to gate.qsocket.io via cloudflare.

Very first problem is race condition where real_gethostbyname is set to nil. I moved it to setup() to make sure it is available in connect() method.

Secondly, I had to move `-lm` to the very end to avoid `undefined symbol: sin` error. 

But after that it threw error from cloudflare, since it appears that qs-proxy as of right now expect to talk to `gate.qsocket.io` directly...

I wonder if this project is abandoned? 

And what are plans for releasing the relay/gate component?

**Comment by EgeBalci** [comment]
Short answer: yes, **qs-proxy** tool is abandoned. We are aware of the errors, because of the recent protocol update, QSRN now has a websocket based authentication mechanism, which this tool does not support. The qs-proxy tool is no longer maintained because redirecting TCP traffic can also be achieved using the [qs-netcat](https://github.com/qsocket/qs-netcat) utility. Feel free to check the usage. As of today, this repository will be archived. Thanks for pointing it out. The source code for the relay will be released at the end of the beta testing phase of this project, we don't have a certain date at the moment.
